#Colocar en este archivo todos los parametos del sistema

#nombre de archivos
linea=linea.txt
parada=parada.txt

#cantidad de pasajeros
cantidadPasajeros=500
capacidadColectivo=30

recorridos.L1 = 2
recorridos.L2 = 5
recorridos.L3 = 2
recorridos.L4 = 5
recorridos.L5 = 3
recorridos.L6 = 2
